import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';

test('PostgreSQL migration: invited identities, tenant isolation, role gates, approvals, revocation and audit',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon; create role authenticated; create role supabase_auth_admin;
 create schema auth; grant usage on schema auth,public to anon,authenticated,supabase_auth_admin;
 create table auth.users(id uuid primary key,email text unique,email_confirmed_at timestamptz,is_anonymous boolean default false);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant execute on function auth.uid() to public;`);
 await db.exec(fs.readFileSync(new URL('../supabase/migrations/202609040001_client_portal.sql',import.meta.url),'utf8'));
 const ids={admin:'10000000-0000-0000-0000-000000000001',a:'10000000-0000-0000-0000-000000000002',b:'10000000-0000-0000-0000-000000000003',staff:'10000000-0000-0000-0000-000000000004',unknown:'10000000-0000-0000-0000-000000000005',unverified:'10000000-0000-0000-0000-000000000006'};
 const pa='20000000-0000-0000-0000-000000000001',pb='20000000-0000-0000-0000-000000000002',ma='30000000-0000-0000-0000-000000000001',mb='30000000-0000-0000-0000-000000000002';
 await db.exec(`insert into auth.users values ${Object.entries(ids).map(([name,id])=>`('${id}','${name}@example.com',${name==='unverified'?'null':'now()'},false)`).join(',')};
 insert into public.portal_staff(email,role) values ('admin@example.com','admin'),('staff@example.com','staff');
 insert into public.portal_projects(id,code,title,client_name) values ('${pa}','PROJ-A','Private A','Company A'),('${pb}','PROJ-B','Private B','Company B');
 insert into public.portal_members(project_id,email,role) values ('${pa}','a@example.com','client'),('${pb}','b@example.com','client'),('${pa}','staff@example.com','staff'),('${pa}','unverified@example.com','client');
 insert into public.portal_milestones(id,project_id,title,status) values ('${ma}','${pa}','A milestone','submitted'),('${mb}','${pb}','B milestone','submitted');
 insert into public.portal_updates(project_id,title,body) values ('${pa}','A update','A private update'),('${pb}','B update','B private update');`);
 const as=async(name,sql)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[name]||'']);await db.exec(name==='anon'?'set role anon':'set role authenticated');return db.query(sql);};
 const denied=async(name,sql)=>{await assert.rejects(()=>as(name,sql));};
 assert.equal((await as('a','select * from portal_projects')).rows.length,1);
 assert.equal((await as('a','select title from portal_projects')).rows[0].title,'Private A');
 assert.equal((await as('a',`select * from portal_projects where id='${pb}'`)).rows.length,0);
 assert.equal((await as('a','select * from portal_milestones')).rows.length,1);
 assert.equal((await as('a','select * from portal_updates')).rows.length,1);
 assert.equal((await as('b',`select * from portal_updates where project_id='${pa}'`)).rows.length,0);
 for(const table of ['projects','members','milestones','updates','requests','staff','audit_events'])await denied('anon',`select * from portal_${table}`);
 assert.equal((await as('unknown','select * from portal_projects')).rows.length,0);
 assert.equal((await as('unverified','select * from portal_projects')).rows.length,0);
 assert.equal((await as('a',`update portal_projects set title='Hacked' where id='${pa}' returning id`)).rows.length,0);
 await denied('a',`insert into portal_projects(code,title,client_name) values('HACK','Hacked','Hacked')`);
 await denied('a',`insert into portal_members(project_id,email) values('${pa}','unknown@example.com')`);
 await denied('a',`update portal_staff set role='admin' where user_id='${ids.a}'`);
 await denied('a',`update portal_members set user_id='${ids.a}'`);
 await denied('a',`insert into portal_requests(project_id,kind,title,body) values('${pb}','change','Attack','Attack')`);
 await denied('a',`insert into portal_requests(project_id,kind,title,body,created_by) values('${pa}','change','Attack','Attack','${ids.b}')`);
 await as('a',`insert into portal_requests(project_id,kind,title,body) values('${pa}','support','Help','Need help') returning id`);
 assert.equal((await as('b','select * from portal_requests')).rows.length,0);
 assert.equal((await as('a',`update portal_requests set status='closed' returning id`)).rows.length,0);
 await denied('a',`update portal_milestones set approved_by='${ids.a}',approved_at=now(),status='approved' where id='${ma}'`);
 assert.equal((await as('a',`update portal_milestones set status='approved' where id='${ma}' returning id`)).rows.length,0);
 const version=(await as('a',`select updated_at::text as version from portal_milestones where id='${ma}'`)).rows[0].version;
 await denied('b',`select portal_approve_milestone('${ma}','${version}')`);
 await denied('a',`select portal_approve_milestone('${ma}','2000-01-01')`);
 await as('a',`select portal_approve_milestone('${ma}','${version}')`);
 assert.equal((await as('a',`select status from portal_milestones where id='${ma}'`)).rows[0].status,'approved');
 await denied('a',`select portal_approve_milestone('${ma}','${version}')`);
 assert.equal((await as('admin',`delete from portal_milestones where id='${ma}' returning id`)).rows.length,0);
 assert.equal((await as('staff','select * from portal_projects')).rows.length,1);
 await as('staff',`update portal_projects set next_action='Reviewed' where id='${pa}'`);
 assert.equal((await as('staff',`update portal_projects set next_action='Attack' where id='${pb}' returning id`)).rows.length,0);
 await denied('staff',`update portal_projects set archived=true where id='${pa}'`);
 await denied('staff',`insert into portal_members(project_id,email) values('${pa}','new@example.com')`);
 assert.equal((await as('admin','select * from portal_projects')).rows.length,2);
 assert((await as('admin','select * from portal_audit_events')).rows.length>0);
 assert.equal((await as('a','select * from portal_audit_events')).rows.length,0);
 await as('admin',`update portal_members set revoked=true where email='a@example.com'`);
 assert.equal((await as('a','select * from portal_projects')).rows.length,0);
 await as('admin',`update portal_members set revoked=false where email='a@example.com';`);
 await db.exec(`reset role; update auth.users set email='changed@example.com' where id='${ids.a}';`);
 assert.equal((await as('a','select * from portal_projects')).rows.length,0);
 await db.exec(`reset role; update auth.users set email='a@example.com' where id='${ids.a}';`);
 await as('admin',`update portal_projects set archived=true where id='${pa}'`);
 assert.equal((await as('a','select * from portal_projects')).rows.length,0);
 await denied('a',`insert into portal_requests(project_id,kind,title,body) values('${pa}','change','Archived','No')`);
 await as('admin',`update portal_projects set archived=false where id='${pa}'`);
 assert.equal((await as('a','select * from portal_projects')).rows.length,1);
 await db.exec('reset role; set role supabase_auth_admin;');
 assert.deepEqual((await db.query(`select portal_before_user_created('{"user":{"email":"a@example.com","app_metadata":{"provider":"email"}}}') as result`)).rows[0].result,{});
 assert((await db.query(`select portal_before_user_created('{"user":{"email":"stranger@example.com"}}') as result`)).rows[0].result.error);
 assert((await db.query(`select portal_before_user_created('{"user":{"email":"a@example.com","app_metadata":{"provider":"google"}}}') as result`)).rows[0].result.error);
 await denied('a',`select portal_before_user_created('{"user":{"email":"a@example.com"}}')`);
 await db.exec(`reset role; insert into public.portal_members(project_id,email) values('${pa}','future@example.com'); insert into auth.users values('10000000-0000-0000-0000-000000000007','future@example.com',null,false);`);
 let row=(await db.query(`select user_id from public.portal_members where email='future@example.com'`)).rows[0];assert.equal(row.user_id,null);
 await db.exec(`update auth.users set email_confirmed_at=now() where email='future@example.com'`);
 row=(await db.query(`select user_id from public.portal_members where email='future@example.com'`)).rows[0];assert.equal(row.user_id,'10000000-0000-0000-0000-000000000007');
 }finally{await db.close();}
});
