export function makeBrief(values){const labels={project:'ชื่อโครงการ',problem:'ปัญหาที่ต้องการแก้',outcome:'ผลลัพธ์ที่คาดหวัง',type:'รูปแบบระบบ',users:'ผู้ใช้งานหลัก',features:'ฟังก์ชันระยะแรก',integration:'ข้อมูล / ระบบที่ต้องเชื่อมต่อ',budget:'งบประมาณตั้งต้น',timeline:'ช่วงเวลาที่ต้องการเริ่ม',constraints:'ข้อกำหนดพิเศษ'};return ['PROJECT BRIEF / MONSTOPIA','',...Object.entries(labels).flatMap(([key,label])=>[label,values[key]?.trim()||'ยังไม่ระบุ','']),'บรีฟนี้ใช้เริ่มต้นพูดคุย ไม่ใช่ใบเสนอราคาหรือข้อตกลงขอบเขตงาน'].join('\n');}
export function initBrief(doc=document){const form=doc.getElementById('brief-form');if(!form)return;let step=0,values={},text='';const sets=[...form.querySelectorAll('fieldset')],steps=[...doc.querySelectorAll('.brief-steps span')],back=doc.getElementById('brief-back'),next=doc.getElementById('brief-next'),output=doc.getElementById('brief-output'),status=doc.getElementById('brief-copy-status');
 const collect=()=>Object.assign(values,Object.fromEntries(new FormData(form)));
 function display(){sets.forEach((set,i)=>{set.hidden=i!==step;set.disabled=i!==step;});steps.forEach((item,i)=>{item.classList.toggle('active',i===step);if(i===step)item.setAttribute('aria-current','step');else item.removeAttribute('aria-current');});form.hidden=step===3;output.hidden=step!==3;back.hidden=step===0;next.textContent=step===2?'สรุปบรีฟของฉัน →':'ถัดไป →';if(step<3)sets[step].querySelector('input,textarea,select').focus();}
 form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;collect();step++;if(step===3){text=makeBrief(values);doc.getElementById('brief-result').textContent=text;const email=doc.getElementById('brief-email');email.href='mailto:contact@monstopia.co.th?subject='+encodeURIComponent('ปรึกษาโครงการ: '+values.project)+'&body='+encodeURIComponent(text);email.hidden=text.length>2500;status.textContent=text.length>2500?'บรีฟมีรายละเอียดมาก กรุณาดาวน์โหลดหรือคัดลอกไปใส่ในอีเมล เพื่อป้องกันข้อความถูกตัด':'';}display();if(step===3)doc.getElementById('brief-result-heading').focus();});
 back.addEventListener('click',()=>{collect();step--;display();});doc.getElementById('brief-edit').addEventListener('click',()=>{step=0;display();});
 doc.getElementById('brief-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(text);status.textContent='คัดลอกบรีฟแล้ว ยังไม่มีการส่งข้อความ';}catch{status.textContent='คัดลอกอัตโนมัติไม่ได้ กรุณาเลือกข้อความหรือดาวน์โหลดไฟล์';}});
 doc.getElementById('brief-download').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));const a=doc.createElement('a');a.href=url;a.download='monstopia-project-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
}
if(typeof document!=='undefined')initBrief();
